spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:meongnyang}
    username: ${DB_USERNAME:meongnyang}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "https://meongnyangtrip.duckdns.org/login/oauth2/code/{registrationId}"

          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "https://meongnyangtrip.duckdns.org/login/oauth2/code/{registrationId}"
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  forward-headers-strategy: framework
  port: 8080
  use-forward-headers: true

pet-tour:
  service-key: ${PET_TOUR_SERVICE_KEY}
  base-url: https://apis.data.go.kr/B551011/KorPetTourService2

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

# 운영: FE 서버 URL로 리다이렉트
oauth2:
  redirect-uri: ${OAUTH2_REDIRECT_URI:https://meongnyangtrip.duckdns.org/oauth2/callback}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false